angular
  .module('portfolioApp', ['ui.router', 'ngAnimate', 'angularMoment'])
  .config(config)
  .factory('artService', artService)
  .factory('blogService', blogService)
  .factory('messageService', messageService)
  .factory('projectsService', projectsService)
  .controller('AboutController', AboutController)
  .controller('ApplicationController', ApplicationController)
  .controller('ArtController', ArtController)
  .controller('BlogController', BlogController)
  .controller('ContactController', ContactController)
  .controller('ProjectsController', ProjectsController)
