angular
  .module('portfolioApp', ['ui.router', 'ngAnimate'])
  .config(config)
  .factory('messageService', messageService)
  .factory('projectsService', projectsService)
  .factory('resourcesService', resourcesService)
  .factory('artService', artService)
  .controller('ApplicationController', ApplicationController)
  .controller('AboutController', AboutController)
  .controller('ProjectsController', ProjectsController)
  .controller('ContactController', ContactController)
  .controller('ResourcesController', ResourcesController)
  .controller('ArtController', ArtController)
